name: Enforce Changelog Label

on:
  pull_request:
    types: [opened, reopened, ready_for_review, labeled, unlabeled]
    
permissions:
  pull-requests: read
    
jobs:
  check_label:
    name: Enforce Changelog Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const required = [
              'changelog:added',
              'changelog:changed',
              'changelog:deprecated',
              'changelog:fixed',
              'changelog:removed',
              'changelog:security',
              'dependencies', // Dependabot updates
            ];

            const pr = context.payload.pull_request;

            // Skip draft PRs to avoid noisy failures during WIP
            if (pr.draft) {
              core.info('Draft PR – skipping changelog-label check.');
              return;
            }

            const labels = pr.labels.map(label => label.name);
            if (!labels.some(label => required.includes(label))) {
              core.setFailed(`Missing changelog label – add one of: ${required.join(', ')}`);
            } else {
              core.info('Changelog label present.');
            }
