name: Release Drafter

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_drafter:
    name: Release Drafter
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
